#Requires -Version 5.1
<#
.SYNOPSIS
  Links ai-configs rules into a project via NTFS HardLinks (no Developer Mode required).

.PARAMETER ProjectDir
  Absolute path to the target project directory.

.PARAMETER Project
  Folder name inside ai-configs that contains the configs to link.

.EXAMPLE
  .\setup-windows.ps1 -ProjectDir "C:\work\THT-myaccount" -Project "THT-myaccount"
  .\setup-windows.ps1 -ProjectDir "D:\projects\my-app" -Project "my-project-name"

.NOTES
  HardLinks require source and target to be on the same drive.
  After a `git pull` in ai-configs run this script again to re-link any new files.
#>

param(
  [Parameter(Mandatory, HelpMessage="Absolute path to the target project")]
  [string]$ProjectDir,

  [Parameter(Mandatory, HelpMessage="Folder name in ai-configs")]
  [string]$Project
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot  = Split-Path -Parent $ScriptDir
$SourceDir = Join-Path $RepoRoot $Project

if (-not (Test-Path $SourceDir -PathType Container)) {
  $available = Get-ChildItem $RepoRoot -Directory |
    Where-Object { $_.Name -notmatch '^(scripts|\.)' } |
    Select-Object -ExpandProperty Name
  Write-Error "Project folder not found: $SourceDir`nAvailable: $($available -join ', ')"
  exit 1
}

function Link-File {
  param([string]$Src, [string]$Dst)

  $dir = Split-Path -Parent $Dst
  if (-not (Test-Path $dir)) {
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
  }

  if (Test-Path $Dst) {
    Remove-Item $Dst -Force
}

  New-Item -ItemType HardLink -Path $Dst -Target $Src | Out-Null
  Write-Host "  linked $Dst"
  Write-Host "      -> $Src"
}

# Read a KEY=value entry from a .env file (ignores comments/blank lines, strips quotes).
function Get-EnvValue {
  param([string]$EnvPath, [string]$Key)
  if (-not (Test-Path $EnvPath)) { return $null }
  foreach ($line in Get-Content $EnvPath) {
    $t = $line.Trim()
    if ($t -eq '' -or $t.StartsWith('#')) { continue }
    $idx = $t.IndexOf('=')
    if ($idx -lt 1) { continue }
    if ($t.Substring(0, $idx).Trim() -ne $Key) { continue }
    $v = $t.Substring($idx + 1).Trim()
    if ($v.Length -ge 2 -and (($v.StartsWith('"') -and $v.EndsWith('"')) -or ($v.StartsWith("'") -and $v.EndsWith("'")))) {
      $v = $v.Substring(1, $v.Length - 2)
    }
    return $v
  }
  return $null
}

# Return the mcpServers object from an MCP json file, or $null.
function Get-McpServers {
  param([string]$Path)
  if (-not (Test-Path $Path)) { return $null }
  $obj = Get-Content $Path -Raw | ConvertFrom-Json
  if ($obj.PSObject.Properties['mcpServers']) { return $obj.mcpServers }
  return $null
}

Write-Host "Project : $Project"
Write-Host "Source  : $SourceDir"
Write-Host "Target  : $ProjectDir"
Write-Host ""

# CLAUDE.md
$f = Join-Path $SourceDir "CLAUDE.md"
if (Test-Path $f) { Link-File $f (Join-Path $ProjectDir "CLAUDE.md") }

# .cursorrules
$f = Join-Path $SourceDir ".cursorrules"
if (Test-Path $f) { Link-File $f (Join-Path $ProjectDir ".cursorrules") }

# .mcp.json — generated by merging the project's Windows MCP source with the shared one.
# Project servers win on key conflict; common adds shortcut. The shortcut API token is
# resolved from automation/.env into the generated (gitignored) file so it never enters git.
$envFile = Join-Path $RepoRoot "automation\.env"
$merged  = [ordered]@{}
foreach ($src in @((Join-Path $RepoRoot "common\.mcp.windows.json"), (Join-Path $SourceDir ".mcp.windows.json"))) {
  $servers = Get-McpServers $src
  if ($servers) {
    foreach ($p in $servers.PSObject.Properties) { $merged[$p.Name] = $p.Value }
  }
}
if ($merged.Count -gt 0) {
  if ($merged.Contains('shortcut') -and $merged['shortcut'].PSObject.Properties['env'] -and
      $merged['shortcut'].env.PSObject.Properties['SHORTCUT_API_TOKEN']) {
    $token = Get-EnvValue $envFile 'SHORTCUT_API_TOKEN'
    if ($token) {
      $merged['shortcut'].env.SHORTCUT_API_TOKEN = $token
    } else {
      Write-Host "  warn: SHORTCUT_API_TOKEN not set in automation/.env - leaving placeholder in .mcp.json"
    }
  }
  $mcpTarget = Join-Path $ProjectDir ".mcp.json"
  if (Test-Path $mcpTarget) { Remove-Item $mcpTarget -Force }
  ([ordered]@{ mcpServers = $merged } | ConvertTo-Json -Depth 20) | Set-Content $mcpTarget -Encoding utf8
  Write-Host "  generated $mcpTarget ($($merged.Keys -join ', '))"
}

# .claude/settings.json — MCP server config
$f = Join-Path $SourceDir ".claude\settings.json"
if (Test-Path $f) { Link-File $f (Join-Path $ProjectDir ".claude\settings.json") }

# .claude/rules/*.md — individual files
$rulesDir = Join-Path $SourceDir ".claude\rules"
if (Test-Path $rulesDir -PathType Container) {
  Get-ChildItem (Join-Path $rulesDir "*.md") | ForEach-Object {
    Link-File $_.FullName (Join-Path $ProjectDir ".claude\rules\$($_.Name)")
  }
}

# common/.claude/commands/*.md — shared commands (linked first; project-specific overrides below)
$commonCommandsDir = Join-Path $RepoRoot "common\.claude\commands"
if (Test-Path $commonCommandsDir -PathType Container) {
  Get-ChildItem (Join-Path $commonCommandsDir "*.md") | ForEach-Object {
    Link-File $_.FullName (Join-Path $ProjectDir ".claude\commands\$($_.Name)")
  }
}

# .claude/commands/*.md — individual files (overrides common if same name)
$commandsDir = Join-Path $SourceDir ".claude\commands"
if (Test-Path $commandsDir -PathType Container) {
  Get-ChildItem (Join-Path $commandsDir "*.md") | ForEach-Object {
    Link-File $_.FullName (Join-Path $ProjectDir ".claude\commands\$($_.Name)")
  }
}

# .claude/settings.local.json — inject AI_CONFIGS_DIR
$settingsLocalPath = Join-Path $ProjectDir ".claude\settings.local.json"
$settingsLocalDir  = Split-Path -Parent $settingsLocalPath
if (-not (Test-Path $settingsLocalDir)) {
  New-Item -ItemType Directory -Path $settingsLocalDir -Force | Out-Null
}

if (Test-Path $settingsLocalPath) {
  $json = Get-Content $settingsLocalPath -Raw | ConvertFrom-Json
} else {
  $json = [PSCustomObject]@{}
}

if (-not $json.PSObject.Properties['env']) {
  $json | Add-Member -MemberType NoteProperty -Name 'env' -Value ([PSCustomObject]@{})
}
$json.env | Add-Member -MemberType NoteProperty -Name 'AI_CONFIGS_DIR' `
  -Value ($RepoRoot -replace '\\', '/') -Force

# SHORTCUT_MEMBER_ID — read from automation/.env so the Shortcut commands can use it via
# $env:SHORTCUT_MEMBER_ID. Stays in the gitignored settings.local.json, never in git.
$memberId = Get-EnvValue $envFile 'SHORTCUT_MEMBER_ID'
if ($memberId) {
  $json.env | Add-Member -MemberType NoteProperty -Name 'SHORTCUT_MEMBER_ID' -Value $memberId -Force
}

$json | ConvertTo-Json -Depth 10 | Set-Content $settingsLocalPath -Encoding utf8
Write-Host "  updated $settingsLocalPath"
Write-Host "     AI_CONFIGS_DIR=$($RepoRoot -replace '\\', '/')"
if ($memberId) { Write-Host "     SHORTCUT_MEMBER_ID=$memberId" }

Write-Host ""
Write-Host "Done."
